### ISSUE TITLE
Adding cycle-by-cycle information in flexpret.

### ISSUE THREAD

**Issue by lsk567** [icyphy/lf-flexpret#9]
Corresponding Rocketchip reference: https://github.com/chipsalliance/rocket-chip/blob/master/src/main/scala/rocket/RocketCore.scala#L977

**Comment by hokeun** [comment]
Youri (@suyourice) found that we might be able to get PC information from here: https://github.com/lsk567/flexpret/blob/d38c4fbb935c9221b8ee4f4c16939eb56673bc6c/src/main/scala/Core/Datapath.scala

**Comment by suyourice** [comment]
I am working on [this branch](https://github.com/lsk567/flexpret/tree/cycle-by-cycle).

**Comment by lsk567** [comment]
Closing this now since [a PR](https://github.com/pretis/flexpret/pull/36) has been filed. Thanks, @suyourice!
